### ISSUE TITLE
Enabling Shaders Creates a Flickering Blackscreen

### ISSUE THREAD

**Issue by brucethemoose** [DrDesten/Stracciatella#5]
Running a Vega 64 GPU w Windows 10 and Oculus/Forge, if that matters. 

I tried both the 1.3 release and commit `7ebe942`, as the latest commit seemingly fails to compile. I've also tried disabling every option I can in the shader options, only the "debug overworld" options removes the blackscreen,

Here's a full log running commit `7ebe942`:

https://0x0.st/ous_.txt

EDIT: And Sildur's shaders seem to work fine on this setup.

**Comment by brucethemoose** [comment]
Here's a log from the color branch, default options: https://0x0.st/ousy.txt

**Comment by DrDesten** [comment]
It seems like you are using Iris shaders / sodium, not Optifine. Stracciatella only works with optifine at the moment

**Comment by DrDesten** [comment]
I don't know about Oculus specifically, but Iris shaders aims to gain parity with optifine, we'll all have to wait for that
