### ISSUE TITLE
Sky bugs with darkness effect

### ISSUE THREAD

**Issue by chocotoneg** [DrDesten/Stracciatella#6]
now in the correct shader, whenever you get darkness by forced(/effect) or natural, your sky bugs with Sky: ON
![178134438-88111e78-65db-4569-92d4-45f25d848f22](https://user-images.githubusercontent.com/98628957/178158584-8d64bae0-b273-4cf7-8277-45eb7f12c424.png)
(OptiFine_1.19_HD_U_H8)

**Comment by DrDesten** [comment]
This bug should be fixed in the next update. I'm struggling with supporting intel integrated graphics rn, that's why it's not released yet.

**Comment by chocotoneg** [comment]
oh that explains alot, the only thing i can do is wait for a new update.(or buy a gpu)
