### ISSUE TITLE
Custom heads display issue

### ISSUE THREAD

**Issue by SnowPowerCore** [DrDesten/Stracciatella#7]
Hello, i have an issue with displaying custom heads when using Stracciatella.

https://user-images.githubusercontent.com/35460261/210372341-03b44289-b09e-4f59-b31d-03fe58ac9ee7.mp4

My system is Windows 11, Minecraft 1.19.2 with Forge and OptiFine v. HD U H9, other mods installed
- Xaeros_Minimap_FP22.16.3_Forge_1.19.1
- XaerosWorldMap_1.28.7_Forge_1.19.1
- InventoryProfilesNext-forge-1.19-1.9.1
- MouseTweaks-forge-mc1.19-2.23
- kotlinforforge-3.8.0-obf
- libIPN-forge-1.19-2.0.1

No external resource packs, only these two
<img width="407" alt="image" src="https://user-images.githubusercontent.com/35460261/210372921-613527c5-21da-403e-9782-faa42c54699f.png">

This issue is on my server Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25). I tested it opening local server in-game, it doesn't reproduce, only with Paper server. No plugins were installed on Paper server.

**Comment by SnowPowerCore** [comment]
I also tested on Paper 1.19.3 - still the same behavior, not sure it's coming from PaperMC.

**Comment by SnowPowerCore** [comment]
What i noticed is custom heads are translucent. This is not a case with normal Steve/Zombie/etc heads, just with custom ones. They're translucent even in local worlds.

**Comment by DrDesten** [comment]
It seems like the heads don't write to a buffer controlling how lit a given pixel is. It might be the lightmap, but I'm not sure.
Some buffers are set to non-clearing in order to increase performance. I think the best option is to add an option for potentially breaking optimisations. Thanks for reporting.

**Comment by DrDesten** [comment]
In 1.19+, it seems like the light map buffer is the only non-clearing one. I'll look into it.

**Comment by SnowPowerCore** [comment]
Do you possibly have a free time to look into this? If not, maybe you could describe on what could be performed and i could look into trying implementing the fix, i'm not familiar with GLSL, but that makes things more interesting for me)

**Comment by DrDesten** [comment]
You can download the shader from the repo, you should see an option "Agressive Optimisation" in the menu. Try turning it off.
I didn't have the time to make a proper release yet, sorry

**Comment by SnowPowerCore** [comment]
Hello, i tried with latest code from main branch, unfortunately, visuals do continue behave like it was shown originally, turning agressive optimization off didn't help.

**Comment by SnowPowerCore** [comment]
Hello, latest release 1.5 does fix the issue, if "Agressive Optimization" is turned off. I'm not sure, if this would be considered as a solution, you might want to just exclude player heads from being translucent completely. But now it looks good. You can close this issue if you think current solution is the way.

**Comment by DrDesten** [comment]
Since I am not sure what exactly causes the issue, I will keep the current "fix" as is.
It doesn't add a performance penalty to those who don't need it, which is an important factor for me.
I am open to revisit this issue when the need arises.
