### ISSUE TITLE
Shader program linking

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [DrDesten/Stracciatella#8]
Game Version: 1.17.1
Shader Version: 1.4.2
Error Log: https://pastebin.com/Z0EscSa9
Shader Loader: Iris

**Comment by mrdiamondmanguydudeman** [comment]
Also im using fabric

**Comment by DrDesten** [comment]
This looks like an Iris issue to me. A code error in the shader *shouldn't* be able to crash minecraft.

**Comment by mrdiamondmanguydudeman** [comment]
ah ok
